### ISSUE TITLE
Recommended stepper motor 

### ISSUE THREAD

**Issue by mgiaco** [mosfet/kossel-minimax#2]
Hello,

Should I go with a default Nema 17 also used on the Kossel mini?

thanks 
Mathias

**Comment by mosfet** [comment]
Yep, no problem, the amount of mass that is moved is minimal, and its
shared evenly across all motors. The 1.2A or 1.7A motors normally used on a
reprap should be fine.

**Comment by mgiaco** [comment]
Thanks that's sounds great.
