### ISSUE TITLE
Carbon-rods?

### ISSUE THREAD

**Issue by mgiaco** [mosfet/kossel-minimax#3]
What kind of carbon rods are you using? The only rods I found are:
http://builda3dprinter.eu/product/carbon-rods-kossel-xl/

thanks

**Comment by mosfet** [comment]
I bought from ebay, search for "6mm OD x 4mm Carbon fiber tube" if you're
using the traxas connectors used in the kossel mini.

**Comment by mgiaco** [comment]
Okay thanks and what about the length I measured 360mm from the CAD.

**Comment by mosfet** [comment]
Yep, I cut mine with a dremel. The length doesn't need to be perfectly
360.22mm long (you'll calibrate that later), but it is important that all
rods are the same length. There is a few guides around that can help
facilitate this, but for me, I strapped the dremel tool with a cutoff blade
to a length of wood, and drilled a small wood endstop about 360mm away from
the cutting blade and trimmed all the rods this way.

**Comment by mgiaco** [comment]
Okay really thanks for your fast support. 
mathias
