### ISSUE TITLE
Extruder

### ISSUE THREAD

**Issue by mgiaco** [mosfet/kossel-minimax#4]
Hello Mosfet,

Do you have any real life picture from the Extruder? We want to build the E3d dual head option. And we are not sure what kind of extruder we should use from your files.

thanks 
mathias

**Comment by mosfet** [comment]
I actually never tested the extruder files, I've always used a wades
extruder with a bowden extension. I've bolted the wades up to the extrusion
using the part wade_mount.

See https://i.imgur.com/KCTG07P.jpg and https://i.imgur.com/Tup3OXS.jpg.

**Comment by mosfet** [comment]
Hmm, unless you're referring to the effector, as there is an effector assembly, but uses multiple configurations in order to switch between effector modes.

I'm not sure if this data was included in the STEP / IGES files, but i can export a particular configuration if need be.

**Comment by mosfet** [comment]
I've uploaded IGES and STEP files for effector_dual_e3d and effector_clip_dual_e3d.

**Comment by mgiaco** [comment]
Thanks
